dofile(minetest.get_modpath("electricity").."/functions.lua")
dofile(minetest.get_modpath("electricity").."/sim.lua")
dofile(minetest.get_modpath("electricity").."/switch.lua")
dofile(minetest.get_modpath("electricity").."/battery.lua")
dofile(minetest.get_modpath("electricity").."/transformer.lua")
dofile(minetest.get_modpath("electricity").."/infinite.lua")
dofile(minetest.get_modpath("electricity").."/cables.lua")
dofile(minetest.get_modpath("electricity").."/multimeter.lua")