name: Loria
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lua and other packages
        run: |
          sudo apt-get install lua5.1
          git clone https://github.com/bakpakin/Fennel
          (cd Fennel && make)

      - name: Build code
        run: PATH=$PATH:`pwd`/Fennel make

      - name: Build .tgz archive
        run: |
          make tar
          mkdir loria
          tar xzf loria.tgz -C loria

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: Loria
          path: loria/

      - name: Check if Git tag exists
        run: |
          git tag --points-at HEAD
          echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Check Git tag name
        run: echo "$HEAD_TAG"

      - name: Make release if Git tag exists
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.HEAD_TAG }}"
          prerelease: false
          files: loria.tgz
        if: ${{ env.HEAD_TAG != '' }}
